name: Build and Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: make

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:

          upload_url: ${{ github.event.release.upload_url }}
          
          asset_path: ./rapl_monitor
          

          asset_name: rapl_monitor
          
          asset_content_type: application/octet-stream
