name: Build and Release

on:
  push:
    tags:
      - 'v*'     # This will trigger on tags like v1.0, v2.0.1, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build
        run: make

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          # You can set 'draft: true' or 'prerelease: true' if you like
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./myprogram        # <--- The path to your compiled binary
          asset_name: myprogram         # <--- The filename visible in the release
          asset_content_type: application/octet-stream
